import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../styles/theme";
import { ContextProvider } from "./context/AppProvider";
import { StoreInitializer } from "./components/StoreInitializer";
import { getUserInfo } from "./utils/userUtils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getUserInfo();


  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <StoreInitializer user={user}>
          <ContextProvider>
            {children}
            </ContextProvider>
            </StoreInitializer>
        </ThemeProvider>
      </body>
    </html>
  );
}
