import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./_styles/theme";
import { ContextProvider } from "./_context/AppProvider";
import { StoreInitializer } from "./_components/StoreInitializer";
import { getUserInfo } from "./_utils/userUtils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getUserInfo();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <StoreInitializer user={user}>
            <ContextProvider>{children}</ContextProvider>
          </StoreInitializer>
        </ThemeProvider>
      </body>
    </html>
  );
}
