export const negativePrompts = [
  {
    title: "Generic",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/64cda0d622cec9423f676916.png",
    keywords: [
      "bad proportions",
      "blurry",
      "boring background",
      "cropped",
      "cut off",
      "disproportioned",
      "distorted",
      "fault",
      "flaw",
      "grains",
      "grainy",
      "hazy",
      "improper scale",
      "incorrect physiology",
      "incorrect ratio",
      "indistinct",
      "low quality",
      "low resolution",
      "pixelated",
      "trimmed",
      "ugly",
      "unfocused",
    ],
  },
  {
    title: "People & Animals",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/655013e4616007b73eb1d948.png",
    keywords: [
      "asymmetric",
      "unnatural",
      "unnatural body",
      "unnatural skin",
      "unnatural skin tone",
      "cross-eyed",
      "disproportionate",
      "poor morphology",
      "incorrect physiology",
      "poor facial details",
      "imperfect anatomy",
      "imperfect ears",
      "imperfect eyes",
      "imperfect face",
      "malformed hands",
      "malformed limbs",
      "additional appendages",
      "additional digits",
      "additional limbs",
      "altered appendages",
      "disconnected limb",
      "fused hand",
      "missing arm",
      "missing leg",
      "missing limb",
    ],
  },
  {
    title: "Nature",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/65512ac984f304e6913a81e4.png",
    keywords: [
      "roads",
      "cars",
      "buildings",
      "city elements",
      "pets",
      "domestic animals",
      "non-native wildlife",
      "fences",
      "artificially colored",
      "oversaturated colors",
      "roads and paths through the habitat",
      "boring",
    ],
  },
  {
    title: "Cityscapes",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/654f360abef0549f910f70a8.png",
    keywords: [
      "asymmetrical buildings",
      "distorted perspective",
      "blurry",
      "close-up",
      "creepy",
      "deformed structures",
      "grainy",
      "jpeg artifacts",
      "low contrast",
      "low quality",
      "lowres",
      "macro",
      "multiple angles",
      "multiple views",
      "overexposed",
      "oversaturated",
      "plain background",
      "solid background",
      "surreal",
      "underexposed",
      "unreal architecture",
      "unreal sky",
      "weird colors",
      "floating objects",
    ],
  },
  {
    title: "Food",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/64cda0d622cec9423f676916.png",
    keywords: [
"blurry",
"unfocused",
"cloned food items",
"unrealistic",
"unnatural",
"unappetizing",
"rotten",
"unhealthy",
"unslightly",
"artificially colored",
"artificial"
    ],
  },
];
