export const negativePrompts = [
  {
    title: "People",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/655013e4616007b73eb1d948.png",
    keywords: [
"absent limbs",
"additional appendages",
"additional digits",
"additional limbs",
"altered appendages",
"amputee",
"asymmetric",
"asymmetric ears",
"bad anatomy",
"bad ears",
"bad eyes",
"bad face",
"bad proportions",
"combined appendages",
"conjoined",
"cropped head",
"cross-eyed",
"disconnected limb",
"disfigured",
"dismembered",
"disproportionate",
"flawed structure",
"fused hand",
"imperfect eyes"  ,    
"incorrect physiology",
"malformed hands",
"malformed limbs",
"missing arm",
"missing leg",
"missing limb",
"poor facial details",
"poor morphology",
"unnatural",
"unnatural body",
"unnatural skin",
"unnatural skin tone",
"weird colors",
    ],
  },
  {
    title: "Animals",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/64cda18f22cec9423f67691a.png",
    keywords: [
      "blurry",
      "boring",
      "close-up",
      "details are low",
      "distorted details",
      "eerie",
      "grains",
      "grainy",
      "low quality",
      "lowres",
      "oversaturated",
      "plain",
      "unattractive",
      "uncreative",
      "underexposed",
    ],
  },
  {
    title: "Nature",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/65512ac984f304e6913a81e4.png",
    keywords: [
      "blurry",
      "boring",
      "close-up",
      "details are low",
      "distorted details",
      "eerie",
      "grains",
      "grainy",
      "low quality",
      "lowres",
      "oversaturated",
      "plain",
      "unattractive",
      "uncreative",
      "underexposed",
    ],
  },
  {
    title: "Architecture",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/65513586f4adf8ea932b06a7.png",
    keywords: [
      "blurry",
      "boring",
      "close-up",
      "details are low",
      "distorted details",
      "eerie",
      "grains",
      "grainy",
      "low quality",
      "lowres",
      "oversaturated",
      "plain",
      "unattractive",
      "uncreative",
      "underexposed",
    ],
  },
  {
    title: "Cityscapes",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/654f360abef0549f910f70a8.png",
    keywords: [
      "asymmetrical buildings",
      "blurry",
      "close-up",
      "creepy",
      "deformed structures",
      "grainy",
      "jpeg artifacts",
      "low contrast",
      "low quality",
      "lowres",
      "macro",
      "multiple angles",
      "multiple views",
      "overexposed",
      "oversaturated",
      "plain background",

      "solid background",
      "surreal",
      "underexposed",
      "unreal architecture",
      "unreal sky",
      "weird colors",
    ],
  },
  {
    title: "Food",
    image_url:
      "https://qrartimages.s3.us-west-1.amazonaws.com/64cda0d622cec9423f676916.png",
    keywords: [
      "blurry",
      "boring",
      "close-up",
      "details are low",
      "distorted details",
      "eerie",
      "grains",
      "grainy",
      "low quality",
      "lowres",
      "oversaturated",
      "plain",
      "unattractive",
      "uncreative",
      "underexposed",
    ],
  },
];
