// Create Who list
const listWho = [
  "An astronaut is",
  "A pepe godzilla is",
  "An alien is",
  "An orang-utan is",
  "A colorful owl is",
  "A nuclear scientist is",
  "An management consultant is",
  "A Villain is",
  "A unicorn is",
  "A pilot is",
  "A Viking is",
  "An animal is",
  "An angry mob is",
  "An officer in rainbow uniform is",
  "A tiger slug is",
  "A chameleon is",
  "A dragon is",
  "A ninja is",
  "A dinosaur is",
  "A robot is",
  "A space monkey is",
  "A neanderthal is",
  "A hippie is",
  "A Warrior is",
  "A Samurai Warrior is",
  "A Bard is",
  "A Clownpunk is",
  "A Caveman is",
  "A Goblin is",
  "A Halfling is",
  "A Wizard is",
  "A Mermaid is",
  "A Humanoid is",
  "A Tiger is",
  "A Corgi is",
  "A Parrot is",
  "A Sandworm is",
  "A Jellyfish is",
  "A Turtle is",
];

// Create What list
const listWhat = [
  "sleeping",
  "walking",
  "running",
  "standing",
  "looking",
  "exploring",
  "creating art",
  "creating a QR code",
  "creating a masterpiece",
  "writing",
  "painting",
  "observing",
  "jumping",
  "eating food",
  "floating",
  "flying",
  "flying a kite",
  "flying a dragon",
  "meditating",
  "waving",
  "swinging",
  "smashing pumpkins",
  "smashing boulders",
  "watching a Solar Eclipse",
  "reading",
  "climbing an elephant",
  "climbing a tree",
  "climbing a limestone rock",
  "performing",
  "cooking",
  "playing",
  "dancing",
  "swimming",
  "relaxing",
  "playing cards",
  "playing music",
  "playing video games",
  "playing the piano",
  "playing the drums",
  "playing the ukulele",
  "playing the alphorn",
  "watching Northern Lights",
];

// Create Where list
const listWhere = [
  "at home",
  "in an office",
  "in a laboratory",
  "at a factory",
  "underwater",
  "in space",
  "on an Alien Planet/Moon",
  "on a Solar System Planet/Moon",
  "at school",
  "at the the park",
  "at the the pool",
  "in the forest",
  "in the Rainforest",
  "in the Jungle",
  "in the Park",
  "at a rangeland",
  "on a pasture",
  "in a Valley",
  "on the Foothills",
  "on the Bayou",
  "on a Glacier",
  "in the Arctic",
  "at the Savanna",
  "at Mesa Bryce",
  "at the Beach",
  "at a Mediterranean town",
  "under the Sea",
  "in the Deep Sea",
  "by a Coral Reef",
  "on a scenic Lake",
  "in a overdimensional Cave",
  "on top of the biggest Mountains",
  "on a volcanic island",
  "in a Wasteland",
  "in a forest of glowing Mushrooms",
  "on an Asteroid",
  "in a Blackhole",
  "within unique Planetary constellation",
  "on Planet Mercury",
  "on Mars",
  "on Jupiter",
  "around the sun",
  "near a Neutron Star",
  "in Outer Space",
];

// Create When list
const listWhen = [
  "in a postapocalyptic setting",
  "in a cyberpunk future",
  "at a scenic full moon night",
  "at early sunrise",
  "at sunset",
  "at dusk",
  "at Midnight",
  "during the 80s",
  "during the 50s",
  "during the 90s",
  "during the Dutch Golden Age",
  "in the middle of winter",
  "in the height of summer",
  "in colorful spring",
  "in the middle of autumn",
  "at the end of the world",
  "in a future where everything is digital",
  "during the Golden Hour",
  "during the Blue Hour",
];

// Create How list
const listHow = [
  "in a car",
  "in a spaceship",
  "in a rocket",
  "on a rover",
  "by a satellite",
  "in a space station",
  "by a space station",
  "on a horse",
  "in an airplane",
  "in a firetruck",
  "in a police car",
  "on a bicycle",
  "on a motorcycle",
  "on a unicycle",
  "on a dinosaur",
  "in a boat",
  "in a seaplane",
];

export const promptKeywords = [
  {title: "Art Styles",
keywords: [
  "Painting By Claude Lorrain",
  "Painting By Pablo Picasso",
  "Painted By Lawrence Pelton",
  "Painting By Van Gogh",
  "Painting By Grant Wood",
  "Painting By Dan Mumford",
  "Painting By Ushio Shinohara",
  "Graffiti By Banksy",
  "Graffiti By Anthony Lister",
  "Cubism",
  "Ukiyo-e Flat Design",
  "Expressionism",
  "Psychedelic",
  "Synesthesia",
  "Pop-Art",
  "Modernism",
  "Constructivism",
  "Positivism",
  "Gothic Horror",
  "Impressionism",
  "Temporary Art",
  "Art Nouveau",
  "Folk Art",
  "Dadaism",
  "Memphis Style",
  "Kitsch",
  "Brocade",
  "Oshibana",
  "Cyberspace",
  "Trillwave",
  "Digitalpunk",
  "Unreal Engine",
  "4k",
  "UHD",
  "3-bit",
  "16-bit",
  "Analog",
  "Pixar",
  "MSPaint",
  "Graphic",
  "Vector Art",
  "3D Render",
  "Low-Poly Art",
  "Pixel Art",
  "Dithering",
  "Flaticon",
  "Glitch Art",
  "Split Toning",
  "Flat Design",
  "Isotype",
  "Isometric",
  "Orthographic",
  "Axonometric",
  "Pictogram",
  "Claymation",
]},
{title: "Cultural Styles",
keywords: [
  "Indian-Style",
  "Soviet-Style",
  "American-Style",
  "Europunk",
  "Incan",
  "Brazilian-Style",
  "Mexican-Style",
  "African-Style",
  "Australian-Style",
  "Spanish-Style",
  "French-Style",
  "Italian-Style",
  "Turkish-Style",
  "German-Style",
  "Greek Mythology",
  "Swiss-Style",
  "Swedish-Style",
  "Roman-Style",
  "Chinese-Style",
  "Japonism",
  "Balinese-Style",
  "Tibetan-Style",
  "Indonesian-Style",
  "Khmer-Style",
  "Indian-Style",
  "Russian-Style",
  "Soviet Propagand",
  "Arabic-Style",
  "Mayan-Style",
  "Caribbean-Style",
  "Egyptian Art",
  "Nordic Mythology",
  "Victorian-Style",
  "Byzantine Icon",
]},
{title: "Medium",
keywords: [
  "Photography",
  "Sketch",
  "Line Art",
  "Graphic Novel",
  "Ink",
  "Flexographic Ink",
  "Viscosity Print",
  "Crayon",
  "Canvas",
  "Watercolor Painting",
  "Encaustic Painting",
  "Gond Painting",
  "Coffee Paint",
  "Graffiti",
  "Sticker",
  "Bagh Print",
  "Tarot Card",
  "Stamp",
  "Origami",
  "Kirigami",
  "Chinese Paper Art",
  "Glass Mosaic",
  "Mural",
  "Mayan Sculpture",
  "Woodblock Print",
  "Collage",
  "Light Art",
  "Sticker Bomb",
  "Installation Art",
  "Negative Space",
  "Outlined",
]},
{title: "Cinematography",
keywords: [
  "Scene",
  "Dramatic",
  "Cinematic",
  "Dramatic",
  "Establishing Shot",
  "Shot on 16mm",
  "Double-Exposure",
  "Depth of Field",
  "Tiltshift",
  "Simplicity",
  "Detailed",
  "Hyperdetailed",
  "Multiplex",
  "Cluttered",
  "Idyllic",
  "Epic Composition",
  "Proportion",
  "Top-View",
  "Parallel Projection",
  "Linear Perspective",
  "Schematic",
  "View From an Airplane",
  "Aerial View",
  "Closeup-View",
  "Epic Wide Shot",
  "Wide Shot",
  "Centered-Shot",
  "First-Person View",
  "Field of View",
  "Low Angle",
  "Macro View",
  "Panorama",
  "Telephoto",
  "Fisheye Lens",
  "Depth",
  "Vantage Point",
  "Vanishing Point",
  "High Angle",
  "Miniature Faking",
  "Forced Perspective",
]},
{title: "Special Effects",
keywords: ["Lumen Reflections",
"Reflection in a Puddle",
"Blur",
"Blur Effect",
"Parallax",
"Anaglyph",
"Chromatic Aberration",
"Posterization",
"Quantization",
"Textured",
"Glowing Edges",
"Repetition",
"Haze",
"Cinematic Haze",
"Bokeh",
"Polaroid",
]}
]

export const promptRandomizer = () => {
const listArtStyles = promptKeywords[0].keywords
const listCulture = promptKeywords[1].keywords
const listMedium = promptKeywords[2].keywords
const listCinematography = promptKeywords[3].keywords
const listSFX = promptKeywords[4].keywords

  //generate random index
  const WhoRandomNum = Math.floor(Math.random() * listWho.length);
  const WhatRandomNum = Math.floor(Math.random() * listWhat.length);
  const WhereRandomNum = Math.floor(Math.random() * listWhere.length);
  const WhenRandomNum = Math.floor(Math.random() * listWhen.length);
  const HowRandomNum = Math.floor(Math.random() * listHow.length);


const artStyleRandomNum = Math.floor(Math.random() * listArtStyles.length)
const cultureRandomNum = Math.floor(Math.random() * listCulture.length)
const mediumRandomNum = Math.floor(Math.random() * listMedium.length)
const cinematographyRandomNum = Math.floor(Math.random() * listCinematography.length)
const SFXRandomNum = Math.floor(Math.random() * listSFX.length)


  //output
  return `${listWho[WhoRandomNum]} ${listWhat[WhatRandomNum]} ${listWhere[WhereRandomNum]} ${listWhen[WhenRandomNum]}, ${listArtStyles[artStyleRandomNum]}, ${listCulture[cultureRandomNum]}, ${listMedium[mediumRandomNum]}, ${listCinematography[cinematographyRandomNum]}`;
}

export default promptRandomizer;
